### ISSUE TITLE
Finish up home page

### ISSUE THREAD

**Issue by jpamental** [jpamental/variable-fonts#144]
Just putting this here as a nudge. I don't have access to the design, but I'm happy to help if I can. This is the last outstanding bit (apart from wanting the toggles) so just don't want to leave it hanging out there.

**Comment by kennethormandy** [comment]
Hi @jpamental, this was on a branch and is done now:

<img width="1030" alt="Screenshot 2020-02-29 16 47 34" src="https://user-images.githubusercontent.com/1581276/75617423-bb1d7e80-5b13-11ea-8f3b-97cfe67b2c1f.png">
<img width="1030" alt="Screenshot 2020-02-29 16 47 37" src="https://user-images.githubusercontent.com/1581276/75617425-be186f00-5b13-11ea-8fdc-0924da67d4f8.png">

### Notes

- All the config and axes data is set via the metadata in the `index.html` file now, so it would be relatively easy to switch fonts, use this component again, etc.
- The design I’m following doesn’t use the sliders anymore, but I didn’t want to rule out that possibility either, so they are actually still part of the build here, but they have `display: none` set. I made sure the new functionality I added still supports the sliders, if we still want to use them.
- I got rid of the folder icon on small screens
- The delayed by character animation plays by default like before, and switches to an all or nothing animation when you click one of the buttons

Since we aren’t using any other dependency, the JS and markup are tied together quite closely. I opted for checking `children` rather than using classes and the query selector on each section of the include, but am happy enough to change that if it’s inconvenient for you. Like I mentioned above, I changed it so the config can be passed in from the `index.html` file, and the CSS animation is generated based on that now too, so hopefully there isn’t a need to change much in the include now anyway.

### Questions

-  *Are we keeping Recursive here, or changing to Roboto Extremo?* I left it as Recursive. If we are sticking with Recursive here, I should probably combine the Italic and Slant axes, per your other discussion. It doesn’t make sense right now to have them as two separate buttons, but would if we are doing Italic with Roboto. Either that, or the buttons need to let you click more than one at a time (this is why I left them as buttons, rather than making them radio or checkbox inputs within the markup—they might need to be either)

***

On larger screens, the header area gets wider than the `.content-section` max width, but only up to a point.

<img width="1550" alt="Screenshot 2020-02-29 16 54 48" src="https://user-images.githubusercontent.com/1581276/75617465-629ab100-5b14-11ea-892b-8b4387a2e9a1.png">

On smaller screens, I have the buttons first, but it would be easy enough to make them second:

<img width="612" alt="Screenshot 2020-02-29 16 55 20" src="https://user-images.githubusercontent.com/1581276/75617467-69292880-5b14-11ea-973f-1362f22aa67d.png">

**Comment by jpamental** [comment]
Hi @kennethormandy - thanks for all of this!

I got this last night on my phone and had a couple of thoughts/questions. 

- I do think we should switch the order so that the font block comes first on small screen

- On iOS (I have an 11 pro, latest updates) when I click the buttons, only the color changes. Nothing happens with the font animation itself.

- Definitely keep Recursive, and I'd get rid of italic and only animate slant

- There are a few 'dark mode' issues on the home page and 'design' page, but I can sort those out if you want to leave that for me

Thanks again! I'll have a closer look at stuff later on today.

**Comment by jpamental** [comment]
Two more notes:
- It's not just iOS where nothing happens with the text when you click the buttons—same thing in Safari on Mac OS. Color changes, but no change in text animation

- Nothing happens with the Slant animation in any browser I've tried (Safari, Chrome, FF)

Let me know if there's anything I can do to help

**Comment by davelab6** [comment]
The 3 links (image + text) at the bottom of the page all link to the same page.

**Comment by jpamental** [comment]
Fixed the typo in the card link code so those are fixed now @davelab6

**Comment by jpamental** [comment]
Just pushed up a bunch of fixes for the broken Slant demo and various dark mode issues. Still not functional in Safari on desktop or iOS though. Haven't had time to look at that.

**Comment by jpamental** [comment]
Well, I haven't figured out yet how to get the different axis animations to 'play' in Safari or iOS, but one thing that will be an issue in all browsers is the infinite looping of the animation. That causes memory buildup errors and crashes just about everywhere. I think it may be better to switch to different named keyframe animations each with their own count, so when they get added/removed it resets the count. 

@kennethormandy I haven't heard anything from you in a few days so I'm sort of assuming I should jump in and try and sort this out, as it doesn't function in iOS or desktop Safari, and since the announcement of the platform update just happened I don't want to delay any further in having a functional site.

@davelab6 if you could confirm it's OK to put in the GF UI content I'll do that as well.

**Comment by litherland** [comment]
Hey @jpamental, does the GF UI content exist in a gdoc somewhere? Want me to take a quick look before you drop it in just to make sure it’s consistent with the rest of the copy? Also just to get another set of eyes on it?

**Comment by jpamental** [comment]
It's a little messy under the hood, but now works in iOS and Safari along with FF and Chrome. I'll clean it up after I can give it a bit more of a think, but at least this is ready to be used.
